apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }} # service port
      targetPort: 8080 # container port